service: hello-world
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2 # US East 2 is in Columbus!
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
